import numpy as np
import pandas as pd
from sklearn.model_selection import RepeatedStratifiedKFold, StratifiedShuffleSplit

def load_spambase_original(filepath="dataset/spambase.data"):
    """Load the original Spambase dataset with its two classes.

    Args:
        filepath: Path to the Spambase data file.

    Returns:
        A tuple containing the feature matrix and the original class labels.
        The last column contains the class labels, where 1 represents spam
        and 0 represents non-spam.
    """
    # The data file has no header, so read it without column names.
    df = pd.read_csv(filepath, header=None)

    # The first 57 columns contain the features.
    X = df.iloc[:, :-1].values
    # The last column contains the target labels.
    y = df.iloc[:, -1].values

    return X, y

def load_spambase_kstar_mock(filepath="dataset/spambase.data", k_star=3, random_state=42):
    """Load the Spambase features with mock labels for ``K*`` classes.

    This is a temporary mock implementation until the Double k-means
    integration is complete.

    Args:
        filepath: Path to the Spambase data file.
        k_star: Number of classes to generate.
        random_state: Seed used to generate reproducible mock labels.

    Returns:
        A tuple containing the feature matrix and randomly generated labels.
    """
    X, _ = load_spambase_original(filepath)

    # Generate random labels to simulate Double k-means output.
    np.random.seed(random_state)
    y_mock = np.random.randint(0, k_star, size=X.shape[0])

    return X, y_mock

def get_nested_cv_splitter():
    """Create a splitter for repeated stratified 10-fold cross-validation.

    Returns:
        A ``RepeatedStratifiedKFold`` configured with 10 folds and 30
        repetitions.
    """
    return RepeatedStratifiedKFold(n_splits=10, n_repeats=30, random_state=42)

def get_learning_curve_splits(X, y):
    """Generate stratified train/test splits for a learning curve.

    Args:
        X: Feature matrix used to generate the splits.
        y: Target labels used for stratification.

    Returns:
        A dictionary mapping each training-set proportion from 0.05 to 0.95
        to a tuple of training and testing indices.
    """
    splits = {}

    # Vary the training-set proportion from 5% to 95% in 5% increments.
    train_sizes = np.arange(0.05, 0.96, 0.05)

    for train_size in train_sizes:
        # Round values to avoid floating-point precision artifacts.
        train_size_rounded = round(train_size, 2)

        # StratifiedShuffleSplit preserves the class distribution in each split.
        splitter = StratifiedShuffleSplit(n_splits=1, train_size=train_size_rounded, random_state=42)

        # Retrieve the only split generated by this splitter.
        train_idx, test_idx = next(splitter.split(X, y))
        splits[train_size_rounded] = (train_idx, test_idx)

    return splits